Repository kubeedge/beehive, pull requests merged in 2019-08, with the labels that each got.

#9 add makefile
  Makefile
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/core/model/message.go
Labels: lgtm, size/M

#25 add owners file for beehive
  OWNERS
Labels: do-not-merge/hold, lgtm, size/S

#10 Travis CI Configuration for Beehive Repo
  .travis.yml
Labels: approved, lgtm
